#include "disk.h"
#include "RAM.h"
#include "PCB.h"
#include "CPU.h"
#include <vector>
#include <iostream>
#include <fstream>
#include <sstream>

int main(){
	CPU cpu;

	//testDisk.loader();

	/* THIS IS THE PSEUDO-CODE FOR OUR DRIVER 

			1. CALL LOADER TO LOAD EVERYTHING INTO DISK AND CREATE PCB VECTOR
			2. CALL LTS TO SORT PCB VECTOR IF PRIORITY SCHEDULING, ELSE PCB VECTOR IS FIFO 
			3. CALL LTS TO LOAD FIRST 15 PROCESSES INTO RAM BASED ON SORTING ORDER (FIFO, PRIORITY)
			4. CALL DISPATCHER TO SELECT PROCESSES FROM RAM (THEY ARE IN ORDER OF SELECTION)
			5. DISPATCHER CALLS LOADCPU METHOD PER PROCESS TO ALLOCATE IT A CPU FOR EXECUTION
			6. CALL FREERAM TO CLEAR RAM AFTER ALL 15 PROCESSES HAVE RUN
			7. REPEAT 3-5 UNTIL ALL JOBS ARE PROCESSED
			8. RECORD TIMING INFORMATION AT SOME UNDETERMINED POINT YET
			9. TERMINATE PROGRAM ONCE ALL 30 ARE FINISHED
		
	*/

	system("pause");
}